package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.example.demo.model.Amazon;
import com.example.demo.repo.AmazonRepo;

@SpringBootApplication
public class SpringdatajpadataStoring1AutoGeneratedApplication implements CommandLineRunner {

	@Autowired
	private AmazonRepo ar;
	public static void main(String[] args) {
		SpringApplication.run(SpringdatajpadataStoring1AutoGeneratedApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		// TODO Auto-generated method stub
		Amazon a=new Amazon();
		a.setProductname("laptop");
		ar.save(a);
		
	}

}
